ALTER TABLE banners
  ADD COLUMN IF NOT EXISTS link_type  VARCHAR(20),
  ADD COLUMN IF NOT EXISTS link_value TEXT,
  ADD COLUMN IF NOT EXISTS bg_color   VARCHAR(7),
  ADD COLUMN IF NOT EXISTS content    TEXT;
